
spring:
  datasource:
    url: { db url }
    username: { db username }
    password: { db password }
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
#          show_sql: true
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: error
    org.hibernate.type: info

log:
  config:
    path: ./logs
    filename: app-master
    maxHistory: 30
    totalSizeCap: 200MB

cloud:
  aws:
    credentials:
      accessKey: ${{ AWS_ACCESS_KEY }}
      secretKey: ${{ AWS_SECRET_ACCESS_KEY }}
    s3:
      bucket: break-the-cycle-use-person-record
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false