#server:
#  ssl:
#    enabled: true
#    key-store: keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: bns-ssl

spring:
  config:
    activate:
      on-profile: jms
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID }
      secretKey: ${AWS_SECRET_ACCESS_KEY }
    s3:
      bucket: break-the-cycle-use-person-record
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false

sms:
  secretKey: ${SMS_SECRET_KEY}
  publicKey: ${SMS_PUBLIC_KEY}
  domain: ${SMS_DOMAIN}
