
spring:
#  datasource:
#    url: { db url }
#    username: { db username }
#    password: { db password }
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none #추후에 validate
    properties:
      hibernate:
        #          show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

log:
  config:
    path: ./logs
    filename: app-dev
    maxHistory: 10
    totalSizeCap: 30MB

cloud:
  aws:
    credentials:
      accessKey: ${{ secrets.AWS_ACCESS_KEY }}
      secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    s3:
      bucket: break-the-cycle-use-person-record
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false