spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/btc
    username: sa
    password: 1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

sms-secret-key: ${SMS_SECRET_KEY}
sms-public-key: ${SMS_PUBLIC_KEY}
sms-domain: ${SMS_DOMAIN}