spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/btc
    username: sa
    password: 1
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


cloud:
  aws:
    credentials:
      profile-name: btc-s3
    s3:
      bucket: break-the-cycle-use-person-record
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false