server:
  port: 8080
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl

  servlet:
    context-path: /api
  encoding:
    charset: UTF-8
    force: true
    force-response: true
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#      location: /media

spring:
  profiles:
    active: dev

  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


