name: break-the-cycle_server #프로젝트 이름

on:
  push:
    branches:
      - develop #브랜치
  workflow_dispatch: #push 외에도 수동 실행 enable

jobs:
  build:
    runs-on: ubuntu-latest #github action 스크립트가 작동될 os 환경

    steps:
      - name: Checkout # 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Set up JDK 17 #JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Grant execute permission for gradlew #gradlew 실행권한 부여
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle #빌드
        run: ./gradlew clean build
        shell: bash